### ISSUE TITLE
FOD in Xiaomi Mi 9 SE not work!

### ISSUE THREAD

**Issue by graypharos** [SDM710-Development/android_kernel_xiaomi_sdm710#14]
Device affected:
Xiaomi Mi 9 SE (GRUS)

Hi,
After adding this org repos to my local_manifests in order to use it for lineage 18.1, I just found out that FOD is not working...
Later after reviewing [android_kernel_xiaomi_sdm710](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710), I just found a workaround that when I reverted these commits:

- [input: tp_goodix_driver: Implement fod_status sysfs attribute](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commit/328ed8fd0c71212de8521acda8bafda8bfa403e4#diff-01bd0ab88e8a5d8bafdb346be277436beb96ee7fdbf340f5b93547e384750769)
- [touchscreen/tp_goodix_driver: Use DEVICE_ATTR_* for sysfs attributes](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commit/b385d87752ce7cadd46d02b192d3bac8408d206e#diff-01bd0ab88e8a5d8bafdb346be277436beb96ee7fdbf340f5b93547e384750769)
- [input: focaltech_touch: Implement fod_status sysfs attribute](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commit/4aa08800b51c8a994e3b6805b3d96544a4568443#diff-9727cc3c20992651a2ef61b205d2b0dee3a747130ae1d30afcd1ca9a1bf54b13)
- [touchscreen/focaltech_touch: Use DEVICE_ATTR_RO for sysfs attributes](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commit/90cad1cc95a798c8c9261c11a84f775454cdbfb5#diff-9727cc3c20992651a2ef61b205d2b0dee3a747130ae1d30afcd1ca9a1bf54b13)
- [touchscreen: Get rid of Xiaomi touch feature](https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commit/c54cd4e429ce5a7e283ff4bf8f2942c07d66c8fe#diff-01bd0ab88e8a5d8bafdb346be277436beb96ee7fdbf340f5b93547e384750769)

 and cherry-pick this commit:
[drivers/input: goodix_ts: Expose fod status](https://github.com/kyasu/android_kernel_xiaomi_sdm710/commit/7d9d8df44fbd3085b5f611369586362f95b3eb86)

It works...
Should I just use the workaround above? or...

Thanks

**Comment by ivecera** [comment]
Fixed by https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/pull/15
